name: 'Setup swagger codegen'
description: 'Sets up swagger-codegen and erlang-generator'
inputs:
  codegen-version:
    description: 'Codegen (swagger-api/swagger-codegen) version to use.'
    required: true
  generator-version:
    description: 'Erlang generator (valitydev/swagger-generator-erlang) version to use.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Java
      shell: bash
      run: java --version

    - name: Create directories
      shell: bash
      run: |
        sudo mkdir -p /usr/local/lib/swagger-codegen
        sudo chown $(whoami) /usr/local/lib/swagger-codegen

    - name: Download swagger-codegen
      shell: bash
      run: |
        wget --no-verbose https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${{ inputs.codegen-version }}/swagger-codegen-cli-${{ inputs.codegen-version }}.jar -O /usr/local/lib/swagger-codegen/swagger-codegen-cli.jar

    - name: Download swagger-generator-erlang
      shell: bash
      run: |
        wget --no-verbose https://github.com/valitydev/swagger-generator-erlang/releases/download/v${{ inputs.generator-version }}/swagger-generator-erlang-v${{ inputs.generator-version }}.jar -O /usr/local/lib/swagger-codegen/swagger-generator-erlang.jar

    - name: Make swagger-codegen shortcut
      shell: bash
      run: |
        echo "#!/bin/sh" > /usr/local/bin/swagger-codegen
        echo "java -cp /usr/local/lib/swagger-codegen/swagger-generator-erlang.jar:/usr/local/lib/swagger-codegen/swagger-codegen-cli.jar io.swagger.codegen.SwaggerCodegen \$*" >> /usr/local/bin/swagger-codegen
        chmod +x /usr/local/bin/swagger-codegen

    - name: Test codegen
      shell: bash
      run: |
        swagger-codegen version
        swagger-codegen langs
