name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: valitydev/action-tagger
          ref: v1
          path: .github/actions/action-tagger

      - uses: ./.github/actions/action-tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
